"use client"

import { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Plus, Trash2, Download, Sparkles, Loader2, GripVertical,
  CheckCircle2, Target, Lightbulb, Star, RefreshCw, ChevronDown, ChevronUp
} from "lucide-react"
import { toast } from "sonner"

interface Experience {
  id: string
  title: string
  company: string
  location: string
  startDate: string
  endDate: string
  description: string
  enhancing?: boolean
}

interface Project {
  id: string
  name: string
  description: string
  technologies: string[]
  link: string
}

interface GeneratedResume {
  professionalSummary: string
  technicalSkills: {
    languages: string[]
    frameworks: string[]
    tools: string[]
    competitiveProgramming: string
  }
  codingAchievements: string[]
  projectSuggestions: { name: string; description: string; technologies: string[]; bullets: string[] }[]
  careerObjective: string
  strengths: string[]
  atsScore: number
  atsKeywords: string[]
  improvementTips: string[]
  suggestedRoles: string[]
}

export function ResumeBuilder() {
  const [targetRole, setTargetRole] = useState("Software Engineer")
  const [additionalInfo, setAdditionalInfo] = useState("")
  const [generating, setGenerating] = useState(false)
  const [generated, setGenerated] = useState<GeneratedResume | null>(null)
  const [generatedAt, setGeneratedAt] = useState<string | null>(null)
  const [showProjectSuggestions, setShowProjectSuggestions] = useState(false)

  const [experiences, setExperiences] = useState<Experience[]>([
    { id: "1", title: "", company: "", location: "", startDate: "", endDate: "", description: "" },
  ])
  const [projects, setProjects] = useState<Project[]>([
    { id: "1", name: "", description: "", technologies: [], link: "" },
  ])

  // ── Generate full AI resume ───────────────────────────────────────────────

  const generateResume = async () => {
    setGenerating(true)
    try {
      const res = await fetch("/api/student/smart-resume/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ targetRole, additionalInfo }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? "Generation failed")
      setGenerated(data.resume)
      setGeneratedAt(data.meta?.generatedAt)
      toast.success("AI resume generated from your verified profile!")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to generate resume")
    } finally {
      setGenerating(false)
    }
  }

  // ── Enhance a single experience with AI ──────────────────────────────────

  const enhanceExperience = async (id: string) => {
    const exp = experiences.find((e) => e.id === id)
    if (!exp) return
    setExperiences((prev) => prev.map((e) => e.id === id ? { ...e, enhancing: true } : e))
    try {
      const res = await fetch("/api/student/smart-resume/enhance", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ title: exp.title, company: exp.company, description: exp.description }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error ?? "Enhancement failed")
      setExperiences((prev) => prev.map((e) => e.id === id ? { ...e, description: data.enhanced, enhancing: false } : e))
      toast.success("Description enhanced by AI!")
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Enhancement failed")
      setExperiences((prev) => prev.map((e) => e.id === id ? { ...e, enhancing: false } : e))
    }
  }

  // ── Download as text ─────────────────────────────────────────────────────

  const downloadResume = () => {
    if (!generated) return
    const lines: string[] = []
    lines.push("═══════════════════════════════════════")
    lines.push("           PROFESSIONAL RESUME")
    lines.push(`  Generated by CodeHiring AI — ${new Date(generatedAt!).toLocaleDateString()}`)
    lines.push("═══════════════════════════════════════\n")
    lines.push("CAREER OBJECTIVE")
    lines.push("─────────────────")
    lines.push(generated.careerObjective + "\n")
    lines.push("PROFESSIONAL SUMMARY")
    lines.push("─────────────────────")
    lines.push(generated.professionalSummary + "\n")
    lines.push("TECHNICAL SKILLS")
    lines.push("─────────────────")
    lines.push(`Languages: ${generated.technicalSkills.languages.join(", ")}`)
    lines.push(`Frameworks: ${generated.technicalSkills.frameworks.join(", ")}`)
    lines.push(`Tools: ${generated.technicalSkills.tools.join(", ")}`)
    lines.push(`Competitive Programming: ${generated.technicalSkills.competitiveProgramming}\n`)
    lines.push("CODING ACHIEVEMENTS")
    lines.push("────────────────────")
    generated.codingAchievements.forEach((a) => lines.push(`• ${a}`))
    lines.push("")
    if (experiences.some((e) => e.title)) {
      lines.push("WORK EXPERIENCE")
      lines.push("────────────────")
      experiences.filter((e) => e.title).forEach((e) => {
        lines.push(`${e.title} | ${e.company} | ${e.location}`)
        lines.push(`${e.startDate} – ${e.endDate}`)
        lines.push(e.description)
        lines.push("")
      })
    }
    if (projects.some((p) => p.name)) {
      lines.push("PROJECTS")
      lines.push("─────────")
      projects.filter((p) => p.name).forEach((p) => {
        lines.push(`${p.name}${p.link ? ` | ${p.link}` : ""}`)
        lines.push(`Technologies: ${p.technologies.join(", ")}`)
        lines.push(p.description)
        lines.push("")
      })
    }
    lines.push("ATS KEYWORDS")
    lines.push("─────────────")
    lines.push(generated.atsKeywords.join(" • "))
    const blob = new Blob([lines.join("\n")], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `resume-${targetRole.replace(/\s+/g, "-").toLowerCase()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  const atsColor = !generated ? "text-muted-foreground" :
    generated.atsScore >= 80 ? "text-emerald-500" :
    generated.atsScore >= 60 ? "text-amber-500" : "text-red-500"

  return (
    <div className="space-y-6">
      {/* ── AI Generation Panel ── */}
      <Card className="border-primary/20 bg-primary/5">
        <CardHeader>
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle>AI Resume Generator</CardTitle>
              <CardDescription>
                Generates a complete resume from your verified coding profile — LeetCode, GitHub, Codeforces & more.
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="space-y-2">
              <Label>Target Role</Label>
              <Input
                placeholder="e.g. Software Engineer, Backend Developer"
                value={targetRole}
                onChange={(e) => setTargetRole(e.target.value)}
              />
            </div>
            <div className="space-y-2">
              <Label>Additional Info <span className="text-muted-foreground text-xs">(optional)</span></Label>
              <Input
                placeholder="e.g. 2 years experience, prefer startup"
                value={additionalInfo}
                onChange={(e) => setAdditionalInfo(e.target.value)}
              />
            </div>
          </div>
          <Button onClick={generateResume} disabled={generating} className="gap-2 w-full sm:w-auto">
            {generating ? (
              <><Loader2 className="h-4 w-4 animate-spin" />Generating with AI...</>
            ) : (
              <><Sparkles className="h-4 w-4" />{generated ? "Regenerate Resume" : "Generate AI Resume"}</>
            )}
          </Button>
          {generated && (
            <p className="text-xs text-muted-foreground">
              Last generated: {new Date(generatedAt!).toLocaleString()} — based on your verified platform data
            </p>
          )}
        </CardContent>
      </Card>

      {/* ── AI Generated Resume Output ── */}
      {generated && (
        <div className="grid gap-6 lg:grid-cols-3">
          {/* Left: main content */}
          <div className="lg:col-span-2 space-y-4">
            {/* ATS Score */}
            <Card>
              <CardContent className="pt-5">
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Target className="h-4 w-4 text-primary" />
                    <span className="text-sm font-semibold text-foreground">ATS Score</span>
                  </div>
                  <span className={`text-2xl font-bold ${atsColor}`}>{generated.atsScore}/100</span>
                </div>
                <div className="h-2 w-full rounded-full bg-secondary">
                  <div
                    className={`h-2 rounded-full transition-all ${generated.atsScore >= 80 ? "bg-emerald-500" : generated.atsScore >= 60 ? "bg-amber-500" : "bg-red-500"}`}
                    style={{ width: `${generated.atsScore}%` }}
                  />
                </div>
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {generated.atsKeywords.map((kw) => (
                    <Badge key={kw} variant="secondary" className="text-xs">{kw}</Badge>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Career Objective */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Career Objective</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground italic leading-relaxed">{generated.careerObjective}</p>
              </CardContent>
            </Card>

            {/* Professional Summary */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Professional Summary</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground leading-relaxed">{generated.professionalSummary}</p>
              </CardContent>
            </Card>

            {/* Technical Skills */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Technical Skills</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {[
                  { label: "Languages", items: generated.technicalSkills.languages },
                  { label: "Frameworks", items: generated.technicalSkills.frameworks },
                  { label: "Tools & Platforms", items: generated.technicalSkills.tools },
                ].map(({ label, items }) => items.length > 0 && (
                  <div key={label}>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">{label}</p>
                    <div className="flex flex-wrap gap-1.5">
                      {items.map((i) => <Badge key={i} variant="outline" className="text-xs">{i}</Badge>)}
                    </div>
                  </div>
                ))}
                {generated.technicalSkills.competitiveProgramming && (
                  <div>
                    <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-1.5">Competitive Programming</p>
                    <p className="text-sm text-foreground">{generated.technicalSkills.competitiveProgramming}</p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Coding Achievements */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-base">Coding Achievements</CardTitle>
                <CardDescription>Generated from your verified platform stats</CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {generated.codingAchievements.map((a, i) => (
                    <li key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <CheckCircle2 className="h-4 w-4 text-emerald-500 mt-0.5 shrink-0" />
                      {a}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Project Suggestions */}
            <Card>
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">AI Project Suggestions</CardTitle>
                  <button onClick={() => setShowProjectSuggestions(!showProjectSuggestions)} className="text-muted-foreground hover:text-foreground">
                    {showProjectSuggestions ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                  </button>
                </div>
                <CardDescription>Projects to build based on your skill set</CardDescription>
              </CardHeader>
              {showProjectSuggestions && (
                <CardContent className="space-y-4">
                  {generated.projectSuggestions.map((p, i) => (
                    <div key={i} className="rounded-lg border border-border p-4">
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <h4 className="text-sm font-semibold text-foreground">{p.name}</h4>
                        <div className="flex flex-wrap gap-1">
                          {p.technologies.map((t) => <Badge key={t} variant="secondary" className="text-[10px]">{t}</Badge>)}
                        </div>
                      </div>
                      <p className="text-xs text-muted-foreground mb-2">{p.description}</p>
                      <ul className="space-y-1">
                        {p.bullets.map((b, j) => (
                          <li key={j} className="text-xs text-muted-foreground flex items-start gap-1.5">
                            <span className="text-primary mt-0.5">•</span>{b}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </CardContent>
              )}
            </Card>
          </div>

          {/* Right: sidebar */}
          <div className="space-y-4">
            {/* Download */}
            <Card className="border-primary/20 bg-primary/5">
              <CardContent className="pt-5">
                <Button onClick={downloadResume} className="w-full gap-2 mb-3">
                  <Download className="h-4 w-4" />Download Resume (.txt)
                </Button>
                <p className="text-xs text-muted-foreground text-center">
                  Copy into Word/Google Docs and format for PDF
                </p>
              </CardContent>
            </Card>

            {/* Strengths */}
            <Card>
              <CardHeader className="pb-2">
                <div className="flex items-center gap-2">
                  <Star className="h-4 w-4 text-amber-500" />
                  <CardTitle className="text-sm">Your Strengths</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="space-y-1.5">
                  {generated.strengths.map((s, i) => (
                    <li key={i} className="text-xs text-muted-foreground flex items-center gap-2">
                      <span className="h-1.5 w-1.5 rounded-full bg-amber-500 shrink-0" />{s}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Improvement Tips */}
            <Card>
              <CardHeader className="pb-2">
                <div className="flex items-center gap-2">
                  <Lightbulb className="h-4 w-4 text-primary" />
                  <CardTitle className="text-sm">Improvement Tips</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {generated.improvementTips.map((tip, i) => (
                    <li key={i} className="text-xs text-muted-foreground flex items-start gap-2">
                      <span className="text-primary mt-0.5 shrink-0">{i + 1}.</span>{tip}
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Suggested Roles */}
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">Suggested Roles</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-1.5">
                  {generated.suggestedRoles.map((r) => (
                    <Badge key={r} className="text-xs bg-primary/10 text-primary border-primary/20">{r}</Badge>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      )}

      <Separator />

      {/* ── Manual Experience Editor ── */}
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="space-y-6">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>Work Experience</CardTitle>
                <CardDescription>Add internships — use AI to enhance descriptions</CardDescription>
              </div>
              <Button onClick={() => setExperiences([...experiences, { id: Date.now().toString(), title: "", company: "", location: "", startDate: "", endDate: "", description: "" }])} size="sm" className="gap-1">
                <Plus className="h-4 w-4" />Add
              </Button>
            </CardHeader>
            <CardContent className="space-y-4">
              {experiences.map((exp, index) => (
                <div key={exp.id} className="space-y-3 rounded-lg border border-border bg-secondary/30 p-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <GripVertical className="h-4 w-4 text-muted-foreground" />
                      <span className="text-xs font-medium text-muted-foreground">Experience {index + 1}</span>
                    </div>
                    <Button variant="ghost" size="icon" onClick={() => setExperiences(experiences.filter((e) => e.id !== exp.id))} className="h-7 w-7 text-destructive hover:text-destructive">
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                  <div className="grid gap-3 sm:grid-cols-2">
                    <div className="space-y-1.5">
                      <Label className="text-xs">Job Title</Label>
                      <Input placeholder="Software Intern" value={exp.title} onChange={(e) => setExperiences(experiences.map((x) => x.id === exp.id ? { ...x, title: e.target.value } : x))} className="h-8 text-sm" />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs">Company</Label>
                      <Input placeholder="Google" value={exp.company} onChange={(e) => setExperiences(experiences.map((x) => x.id === exp.id ? { ...x, company: e.target.value } : x))} className="h-8 text-sm" />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs">Start Date</Label>
                      <Input placeholder="May 2024" value={exp.startDate} onChange={(e) => setExperiences(experiences.map((x) => x.id === exp.id ? { ...x, startDate: e.target.value } : x))} className="h-8 text-sm" />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs">End Date</Label>
                      <Input placeholder="Jul 2024 / Present" value={exp.endDate} onChange={(e) => setExperiences(experiences.map((x) => x.id === exp.id ? { ...x, endDate: e.target.value } : x))} className="h-8 text-sm" />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <div className="flex items-center justify-between">
                      <Label className="text-xs">Description</Label>
                      <Button variant="ghost" size="sm" onClick={() => enhanceExperience(exp.id)} disabled={exp.enhancing || !exp.title} className="h-6 gap-1 text-xs text-primary hover:text-primary/80 px-2">
                        {exp.enhancing ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
                        Enhance with AI
                      </Button>
                    </div>
                    <Textarea
                      placeholder="Describe your responsibilities..."
                      rows={3}
                      value={exp.description}
                      onChange={(e) => setExperiences(experiences.map((x) => x.id === exp.id ? { ...x, description: e.target.value } : x))}
                      className="text-sm resize-none"
                    />
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Projects */}
        <div>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle>Projects</CardTitle>
                <CardDescription>Add your best projects</CardDescription>
              </div>
              <Button onClick={() => setProjects([...projects, { id: Date.now().toString(), name: "", description: "", technologies: [], link: "" }])} size="sm" className="gap-1">
                <Plus className="h-4 w-4" />Add
              </Button>
            </CardHeader>
            <CardContent className="space-y-4">
              {projects.map((proj, index) => (
                <div key={proj.id} className="space-y-3 rounded-lg border border-border bg-secondary/30 p-4">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-medium text-muted-foreground">Project {index + 1}</span>
                    <Button variant="ghost" size="icon" onClick={() => setProjects(projects.filter((p) => p.id !== proj.id))} className="h-7 w-7 text-destructive hover:text-destructive">
                      <Trash2 className="h-3.5 w-3.5" />
                    </Button>
                  </div>
                  <div className="grid gap-3 sm:grid-cols-2">
                    <div className="space-y-1.5">
                      <Label className="text-xs">Project Name</Label>
                      <Input placeholder="My Project" value={proj.name} onChange={(e) => setProjects(projects.map((p) => p.id === proj.id ? { ...p, name: e.target.value } : p))} className="h-8 text-sm" />
                    </div>
                    <div className="space-y-1.5">
                      <Label className="text-xs">GitHub / Link</Label>
                      <Input placeholder="https://github.com/..." value={proj.link} onChange={(e) => setProjects(projects.map((p) => p.id === proj.id ? { ...p, link: e.target.value } : p))} className="h-8 text-sm" />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs">Description</Label>
                    <Textarea placeholder="What does it do?" rows={2} value={proj.description} onChange={(e) => setProjects(projects.map((p) => p.id === proj.id ? { ...p, description: e.target.value } : p))} className="text-sm resize-none" />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs">Technologies</Label>
                    <div className="flex flex-wrap gap-1 mb-1">
                      {proj.technologies.map((t) => (
                        <Badge key={t} variant="secondary" className="text-xs gap-1 cursor-pointer" onClick={() => setProjects(projects.map((p) => p.id === proj.id ? { ...p, technologies: p.technologies.filter((x) => x !== t) } : p))}>
                          {t} ×
                        </Badge>
                      ))}
                    </div>
                    <Input
                      placeholder="Type tech and press Enter"
                      className="h-8 text-sm"
                      onKeyDown={(e) => {
                        if (e.key === "Enter" && e.currentTarget.value.trim()) {
                          const techs = e.currentTarget.value.split(",").map((t) => t.trim()).filter(Boolean)
                          setProjects(projects.map((p) => p.id === proj.id ? { ...p, technologies: [...new Set([...p.technologies, ...techs])] } : p))
                          e.currentTarget.value = ""
                        }
                      }}
                    />
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
