/**
 * Topic Questions — 7 most-asked LeetCode problems per topic
 * Used by the Skill Badge Challenges system
 */

export interface TopicQuestion {
  id: string          // unique badge id
  title: string       // problem name
  url: string         // LeetCode URL
  difficulty: "Easy" | "Medium" | "Hard"
  xp: number
}

export interface TopicData {
  track: string
  label: string
  color: string
  questions: TopicQuestion[]
}

export const TOPIC_QUESTIONS: TopicData[] = [
  { track:"arrays", label:"Arrays", color:"#10b981", questions:[
    { id:"arr-q1", title:"Two Sum",                         url:"https://leetcode.com/problems/two-sum/",                              difficulty:"Easy",   xp:20 },
    { id:"arr-q2", title:"Best Time to Buy and Sell Stock", url:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",      difficulty:"Easy",   xp:20 },
    { id:"arr-q3", title:"Contains Duplicate",              url:"https://leetcode.com/problems/contains-duplicate/",                   difficulty:"Easy",   xp:20 },
    { id:"arr-q4", title:"Product of Array Except Self",    url:"https://leetcode.com/problems/product-of-array-except-self/",         difficulty:"Medium", xp:30 },
    { id:"arr-q5", title:"Maximum Subarray",                url:"https://leetcode.com/problems/maximum-subarray/",                     difficulty:"Medium", xp:30 },
    { id:"arr-q6", title:"Maximum Product Subarray",        url:"https://leetcode.com/problems/maximum-product-subarray/",             difficulty:"Medium", xp:30 },
    { id:"arr-q7", title:"Merge Intervals",                 url:"https://leetcode.com/problems/merge-intervals/",                      difficulty:"Medium", xp:30 },
  ]},
  { track:"strings", label:"Strings", color:"#10b981", questions:[
    { id:"str-q1", title:"Valid Anagram",                   url:"https://leetcode.com/problems/valid-anagram/",                        difficulty:"Easy",   xp:20 },
    { id:"str-q2", title:"Valid Palindrome",                url:"https://leetcode.com/problems/valid-palindrome/",                     difficulty:"Easy",   xp:20 },
    { id:"str-q3", title:"Longest Substring Without Repeating Characters", url:"https://leetcode.com/problems/longest-substring-without-repeating-characters/", difficulty:"Medium", xp:30 },
    { id:"str-q4", title:"Group Anagrams",                  url:"https://leetcode.com/problems/group-anagrams/",                       difficulty:"Medium", xp:30 },
    { id:"str-q5", title:"Longest Palindromic Substring",   url:"https://leetcode.com/problems/longest-palindromic-substring/",        difficulty:"Medium", xp:30 },
    { id:"str-q6", title:"Encode and Decode Strings",       url:"https://leetcode.com/problems/encode-and-decode-strings/",            difficulty:"Medium", xp:30 },
    { id:"str-q7", title:"Minimum Window Substring",        url:"https://leetcode.com/problems/minimum-window-substring/",             difficulty:"Hard",   xp:40 },
  ]},
  { track:"matrix", label:"Matrix", color:"#10b981", questions:[
    { id:"mat-q1", title:"Set Matrix Zeroes",               url:"https://leetcode.com/problems/set-matrix-zeroes/",                    difficulty:"Medium", xp:30 },
    { id:"mat-q2", title:"Spiral Matrix",                   url:"https://leetcode.com/problems/spiral-matrix/",                        difficulty:"Medium", xp:30 },
    { id:"mat-q3", title:"Rotate Image",                    url:"https://leetcode.com/problems/rotate-image/",                         difficulty:"Medium", xp:30 },
    { id:"mat-q4", title:"Word Search",                     url:"https://leetcode.com/problems/word-search/",                          difficulty:"Medium", xp:30 },
    { id:"mat-q5", title:"Number of Islands",               url:"https://leetcode.com/problems/number-of-islands/",                    difficulty:"Medium", xp:30 },
    { id:"mat-q6", title:"Search a 2D Matrix",              url:"https://leetcode.com/problems/search-a-2d-matrix/",                   difficulty:"Medium", xp:30 },
    { id:"mat-q7", title:"Game of Life",                    url:"https://leetcode.com/problems/game-of-life/",                         difficulty:"Medium", xp:30 },
  ]},
  { track:"hashing", label:"Hashing", color:"#3b82f6", questions:[
    { id:"hsh-q1", title:"Two Sum",                         url:"https://leetcode.com/problems/two-sum/",                              difficulty:"Easy",   xp:20 },
    { id:"hsh-q2", title:"Ransom Note",                     url:"https://leetcode.com/problems/ransom-note/",                          difficulty:"Easy",   xp:20 },
    { id:"hsh-q3", title:"Isomorphic Strings",              url:"https://leetcode.com/problems/isomorphic-strings/",                   difficulty:"Easy",   xp:20 },
    { id:"hsh-q4", title:"Group Anagrams",                  url:"https://leetcode.com/problems/group-anagrams/",                       difficulty:"Medium", xp:30 },
    { id:"hsh-q5", title:"Top K Frequent Elements",         url:"https://leetcode.com/problems/top-k-frequent-elements/",              difficulty:"Medium", xp:30 },
    { id:"hsh-q6", title:"Subarray Sum Equals K",           url:"https://leetcode.com/problems/subarray-sum-equals-k/",               difficulty:"Medium", xp:30 },
    { id:"hsh-q7", title:"LRU Cache",                       url:"https://leetcode.com/problems/lru-cache/",                            difficulty:"Medium", xp:30 },
  ]},
  { track:"linked-list", label:"Linked List", color:"#3b82f6", questions:[
    { id:"ll-q1", title:"Reverse Linked List",              url:"https://leetcode.com/problems/reverse-linked-list/",                  difficulty:"Easy",   xp:20 },
    { id:"ll-q2", title:"Merge Two Sorted Lists",           url:"https://leetcode.com/problems/merge-two-sorted-lists/",              difficulty:"Easy",   xp:20 },
    { id:"ll-q3", title:"Linked List Cycle",                url:"https://leetcode.com/problems/linked-list-cycle/",                   difficulty:"Easy",   xp:20 },
    { id:"ll-q4", title:"Remove Nth Node From End",         url:"https://leetcode.com/problems/remove-nth-node-from-end-of-list/",    difficulty:"Medium", xp:30 },
    { id:"ll-q5", title:"Reorder List",                     url:"https://leetcode.com/problems/reorder-list/",                        difficulty:"Medium", xp:30 },
    { id:"ll-q6", title:"Find the Duplicate Number",        url:"https://leetcode.com/problems/find-the-duplicate-number/",           difficulty:"Medium", xp:30 },
    { id:"ll-q7", title:"Merge K Sorted Lists",             url:"https://leetcode.com/problems/merge-k-sorted-lists/",               difficulty:"Hard",   xp:40 },
  ]},
  { track:"stack", label:"Stack", color:"#3b82f6", questions:[
    { id:"stk-q1", title:"Valid Parentheses",               url:"https://leetcode.com/problems/valid-parentheses/",                   difficulty:"Easy",   xp:20 },
    { id:"stk-q2", title:"Min Stack",                       url:"https://leetcode.com/problems/min-stack/",                           difficulty:"Medium", xp:30 },
    { id:"stk-q3", title:"Evaluate Reverse Polish Notation",url:"https://leetcode.com/problems/evaluate-reverse-polish-notation/",    difficulty:"Medium", xp:30 },
    { id:"stk-q4", title:"Generate Parentheses",            url:"https://leetcode.com/problems/generate-parentheses/",               difficulty:"Medium", xp:30 },
    { id:"stk-q5", title:"Daily Temperatures",              url:"https://leetcode.com/problems/daily-temperatures/",                  difficulty:"Medium", xp:30 },
    { id:"stk-q6", title:"Car Fleet",                       url:"https://leetcode.com/problems/car-fleet/",                           difficulty:"Medium", xp:30 },
    { id:"stk-q7", title:"Largest Rectangle in Histogram",  url:"https://leetcode.com/problems/largest-rectangle-in-histogram/",     difficulty:"Hard",   xp:40 },
  ]},
  { track:"queue", label:"Queue", color:"#3b82f6", questions:[
    { id:"que-q1", title:"Implement Queue Using Stacks",    url:"https://leetcode.com/problems/implement-queue-using-stacks/",        difficulty:"Easy",   xp:20 },
    { id:"que-q2", title:"Number of Recent Calls",          url:"https://leetcode.com/problems/number-of-recent-calls/",              difficulty:"Easy",   xp:20 },
    { id:"que-q3", title:"Design Circular Queue",           url:"https://leetcode.com/problems/design-circular-queue/",              difficulty:"Medium", xp:30 },
    { id:"que-q4", title:"Task Scheduler",                  url:"https://leetcode.com/problems/task-scheduler/",                      difficulty:"Medium", xp:30 },
    { id:"que-q5", title:"Rotting Oranges",                 url:"https://leetcode.com/problems/rotting-oranges/",                     difficulty:"Medium", xp:30 },
    { id:"que-q6", title:"Walls and Gates",                 url:"https://leetcode.com/problems/walls-and-gates/",                     difficulty:"Medium", xp:30 },
    { id:"que-q7", title:"Sliding Window Maximum",          url:"https://leetcode.com/problems/sliding-window-maximum/",              difficulty:"Hard",   xp:40 },
  ]},
  { track:"deque", label:"Deque", color:"#f59e0b", questions:[
    { id:"deq-q1", title:"Design Circular Deque",           url:"https://leetcode.com/problems/design-circular-deque/",              difficulty:"Medium", xp:30 },
    { id:"deq-q2", title:"Sliding Window Maximum",          url:"https://leetcode.com/problems/sliding-window-maximum/",              difficulty:"Hard",   xp:40 },
    { id:"deq-q3", title:"Jump Game VI",                    url:"https://leetcode.com/problems/jump-game-vi/",                        difficulty:"Medium", xp:30 },
    { id:"deq-q4", title:"Maximum of Subarrays of Size K",  url:"https://leetcode.com/problems/sliding-window-maximum/",              difficulty:"Hard",   xp:40 },
    { id:"deq-q5", title:"Shortest Subarray with Sum K",    url:"https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", difficulty:"Hard", xp:40 },
    { id:"deq-q6", title:"First Unique Character",          url:"https://leetcode.com/problems/first-unique-character-in-a-string/", difficulty:"Easy",   xp:20 },
    { id:"deq-q7", title:"Constrained Subsequence Sum",     url:"https://leetcode.com/problems/constrained-subsequence-sum/",         difficulty:"Hard",   xp:40 },
  ]},
  { track:"heap", label:"Heap (Priority Queue)", color:"#f59e0b", questions:[
    { id:"hp-q1", title:"Kth Largest Element in Array",     url:"https://leetcode.com/problems/kth-largest-element-in-an-array/",    difficulty:"Medium", xp:30 },
    { id:"hp-q2", title:"Top K Frequent Elements",          url:"https://leetcode.com/problems/top-k-frequent-elements/",             difficulty:"Medium", xp:30 },
    { id:"hp-q3", title:"Find Median from Data Stream",     url:"https://leetcode.com/problems/find-median-from-data-stream/",        difficulty:"Hard",   xp:40 },
    { id:"hp-q4", title:"Task Scheduler",                   url:"https://leetcode.com/problems/task-scheduler/",                      difficulty:"Medium", xp:30 },
    { id:"hp-q5", title:"K Closest Points to Origin",       url:"https://leetcode.com/problems/k-closest-points-to-origin/",         difficulty:"Medium", xp:30 },
    { id:"hp-q6", title:"Merge K Sorted Lists",             url:"https://leetcode.com/problems/merge-k-sorted-lists/",               difficulty:"Hard",   xp:40 },
    { id:"hp-q7", title:"Design Twitter",                   url:"https://leetcode.com/problems/design-twitter/",                      difficulty:"Medium", xp:30 },
  ]},
  { track:"tree", label:"Tree", color:"#f59e0b", questions:[
    { id:"tr-q1", title:"Invert Binary Tree",               url:"https://leetcode.com/problems/invert-binary-tree/",                  difficulty:"Easy",   xp:20 },
    { id:"tr-q2", title:"Maximum Depth of Binary Tree",     url:"https://leetcode.com/problems/maximum-depth-of-binary-tree/",        difficulty:"Easy",   xp:20 },
    { id:"tr-q3", title:"Diameter of Binary Tree",          url:"https://leetcode.com/problems/diameter-of-binary-tree/",             difficulty:"Easy",   xp:20 },
    { id:"tr-q4", title:"Balanced Binary Tree",             url:"https://leetcode.com/problems/balanced-binary-tree/",               difficulty:"Easy",   xp:20 },
    { id:"tr-q5", title:"Same Tree",                        url:"https://leetcode.com/problems/same-tree/",                           difficulty:"Easy",   xp:20 },
    { id:"tr-q6", title:"Subtree of Another Tree",          url:"https://leetcode.com/problems/subtree-of-another-tree/",             difficulty:"Easy",   xp:20 },
    { id:"tr-q7", title:"Path Sum",                         url:"https://leetcode.com/problems/path-sum/",                            difficulty:"Easy",   xp:20 },
  ]},
  { track:"binary-tree", label:"Binary Tree", color:"#f59e0b", questions:[
    { id:"bt-q1", title:"Binary Tree Level Order Traversal", url:"https://leetcode.com/problems/binary-tree-level-order-traversal/",  difficulty:"Medium", xp:30 },
    { id:"bt-q2", title:"Binary Tree Right Side View",       url:"https://leetcode.com/problems/binary-tree-right-side-view/",        difficulty:"Medium", xp:30 },
    { id:"bt-q3", title:"Count Good Nodes in Binary Tree",   url:"https://leetcode.com/problems/count-good-nodes-in-binary-tree/",    difficulty:"Medium", xp:30 },
    { id:"bt-q4", title:"Binary Tree Maximum Path Sum",      url:"https://leetcode.com/problems/binary-tree-maximum-path-sum/",       difficulty:"Hard",   xp:40 },
    { id:"bt-q5", title:"Construct Binary Tree from Preorder and Inorder", url:"https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", difficulty:"Medium", xp:30 },
    { id:"bt-q6", title:"Serialize and Deserialize Binary Tree", url:"https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", difficulty:"Hard", xp:40 },
    { id:"bt-q7", title:"Lowest Common Ancestor of Binary Tree", url:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", difficulty:"Medium", xp:30 },
  ]},
  { track:"bst", label:"Binary Search Tree (BST)", color:"#f59e0b", questions:[
    { id:"bst-q1", title:"Validate Binary Search Tree",     url:"https://leetcode.com/problems/validate-binary-search-tree/",         difficulty:"Medium", xp:30 },
    { id:"bst-q2", title:"Kth Smallest Element in BST",    url:"https://leetcode.com/problems/kth-smallest-element-in-a-bst/",       difficulty:"Medium", xp:30 },
    { id:"bst-q3", title:"LCA of BST",                     url:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty:"Medium", xp:30 },
    { id:"bst-q4", title:"Insert into BST",                url:"https://leetcode.com/problems/insert-into-a-binary-search-tree/",    difficulty:"Medium", xp:30 },
    { id:"bst-q5", title:"Delete Node in BST",             url:"https://leetcode.com/problems/delete-node-in-a-bst/",               difficulty:"Medium", xp:30 },
    { id:"bst-q6", title:"BST Iterator",                   url:"https://leetcode.com/problems/binary-search-tree-iterator/",         difficulty:"Medium", xp:30 },
    { id:"bst-q7", title:"Recover Binary Search Tree",     url:"https://leetcode.com/problems/recover-binary-search-tree/",          difficulty:"Medium", xp:30 },
  ]},
  { track:"trie", label:"Trie", color:"#ef4444", questions:[
    { id:"trie-q1", title:"Implement Trie (Prefix Tree)",   url:"https://leetcode.com/problems/implement-trie-prefix-tree/",          difficulty:"Medium", xp:30 },
    { id:"trie-q2", title:"Design Add and Search Words",    url:"https://leetcode.com/problems/design-add-and-search-words-data-structure/", difficulty:"Medium", xp:30 },
    { id:"trie-q3", title:"Word Search II",                 url:"https://leetcode.com/problems/word-search-ii/",                      difficulty:"Hard",   xp:40 },
    { id:"trie-q4", title:"Replace Words",                  url:"https://leetcode.com/problems/replace-words/",                       difficulty:"Medium", xp:30 },
    { id:"trie-q5", title:"Maximum XOR of Two Numbers",     url:"https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/", difficulty:"Medium", xp:30 },
    { id:"trie-q6", title:"Search Suggestions System",      url:"https://leetcode.com/problems/search-suggestions-system/",           difficulty:"Medium", xp:30 },
    { id:"trie-q7", title:"Word Break II",                  url:"https://leetcode.com/problems/word-break-ii/",                       difficulty:"Hard",   xp:40 },
  ]},
  { track:"graph", label:"Graph", color:"#f59e0b", questions:[
    { id:"gr-q1", title:"Number of Islands",                url:"https://leetcode.com/problems/number-of-islands/",                   difficulty:"Medium", xp:30 },
    { id:"gr-q2", title:"Clone Graph",                      url:"https://leetcode.com/problems/clone-graph/",                         difficulty:"Medium", xp:30 },
    { id:"gr-q3", title:"Max Area of Island",               url:"https://leetcode.com/problems/max-area-of-island/",                  difficulty:"Medium", xp:30 },
    { id:"gr-q4", title:"Pacific Atlantic Water Flow",      url:"https://leetcode.com/problems/pacific-atlantic-water-flow/",         difficulty:"Medium", xp:30 },
    { id:"gr-q5", title:"Surrounded Regions",               url:"https://leetcode.com/problems/surrounded-regions/",                  difficulty:"Medium", xp:30 },
    { id:"gr-q6", title:"Rotting Oranges",                  url:"https://leetcode.com/problems/rotting-oranges/",                     difficulty:"Medium", xp:30 },
    { id:"gr-q7", title:"Course Schedule",                  url:"https://leetcode.com/problems/course-schedule/",                     difficulty:"Medium", xp:30 },
  ]},
  { track:"greedy", label:"Greedy Algorithms", color:"#f59e0b", questions:[
    { id:"grd-q1", title:"Jump Game",                       url:"https://leetcode.com/problems/jump-game/",                           difficulty:"Medium", xp:30 },
    { id:"grd-q2", title:"Jump Game II",                    url:"https://leetcode.com/problems/jump-game-ii/",                        difficulty:"Medium", xp:30 },
    { id:"grd-q3", title:"Gas Station",                     url:"https://leetcode.com/problems/gas-station/",                         difficulty:"Medium", xp:30 },
    { id:"grd-q4", title:"Hand of Straights",               url:"https://leetcode.com/problems/hand-of-straights/",                   difficulty:"Medium", xp:30 },
    { id:"grd-q5", title:"Merge Triplets to Form Target",   url:"https://leetcode.com/problems/merge-triplets-to-form-target-triplet/", difficulty:"Medium", xp:30 },
    { id:"grd-q6", title:"Partition Labels",                url:"https://leetcode.com/problems/partition-labels/",                    difficulty:"Medium", xp:30 },
    { id:"grd-q7", title:"Valid Parenthesis String",        url:"https://leetcode.com/problems/valid-parenthesis-string/",            difficulty:"Medium", xp:30 },
  ]},
  { track:"dp", label:"Dynamic Programming (DP)", color:"#ef4444", questions:[
    { id:"dp-q1", title:"Climbing Stairs",                  url:"https://leetcode.com/problems/climbing-stairs/",                     difficulty:"Easy",   xp:20 },
    { id:"dp-q2", title:"House Robber",                     url:"https://leetcode.com/problems/house-robber/",                        difficulty:"Medium", xp:30 },
    { id:"dp-q3", title:"Longest Common Subsequence",       url:"https://leetcode.com/problems/longest-common-subsequence/",          difficulty:"Medium", xp:30 },
    { id:"dp-q4", title:"Word Break",                       url:"https://leetcode.com/problems/word-break/",                          difficulty:"Medium", xp:30 },
    { id:"dp-q5", title:"Coin Change",                      url:"https://leetcode.com/problems/coin-change/",                         difficulty:"Medium", xp:30 },
    { id:"dp-q6", title:"0/1 Knapsack (Partition Equal Subset Sum)", url:"https://leetcode.com/problems/partition-equal-subset-sum/", difficulty:"Medium", xp:30 },
    { id:"dp-q7", title:"Longest Increasing Subsequence",   url:"https://leetcode.com/problems/longest-increasing-subsequence/",      difficulty:"Medium", xp:30 },
  ]},
  { track:"recursion", label:"Recursion", color:"#f59e0b", questions:[
    { id:"rec-q1", title:"Fibonacci Number",                url:"https://leetcode.com/problems/fibonacci-number/",                    difficulty:"Easy",   xp:20 },
    { id:"rec-q2", title:"Power of Two",                    url:"https://leetcode.com/problems/power-of-two/",                        difficulty:"Easy",   xp:20 },
    { id:"rec-q3", title:"Reverse String",                  url:"https://leetcode.com/problems/reverse-string/",                      difficulty:"Easy",   xp:20 },
    { id:"rec-q4", title:"Merge Two Sorted Lists",          url:"https://leetcode.com/problems/merge-two-sorted-lists/",              difficulty:"Easy",   xp:20 },
    { id:"rec-q5", title:"Flatten Nested List Iterator",    url:"https://leetcode.com/problems/flatten-nested-list-iterator/",        difficulty:"Medium", xp:30 },
    { id:"rec-q6", title:"Letter Combinations of Phone Number", url:"https://leetcode.com/problems/letter-combinations-of-a-phone-number/", difficulty:"Medium", xp:30 },
    { id:"rec-q7", title:"Pow(x, n)",                       url:"https://leetcode.com/problems/powx-n/",                              difficulty:"Medium", xp:30 },
  ]},
  { track:"backtrack", label:"Backtracking", color:"#ef4444", questions:[
    { id:"bkt-q1", title:"Subsets",                         url:"https://leetcode.com/problems/subsets/",                             difficulty:"Medium", xp:30 },
    { id:"bkt-q2", title:"Combination Sum",                 url:"https://leetcode.com/problems/combination-sum/",                     difficulty:"Medium", xp:30 },
    { id:"bkt-q3", title:"Permutations",                    url:"https://leetcode.com/problems/permutations/",                        difficulty:"Medium", xp:30 },
    { id:"bkt-q4", title:"Subsets II",                      url:"https://leetcode.com/problems/subsets-ii/",                          difficulty:"Medium", xp:30 },
    { id:"bkt-q5", title:"Word Search",                     url:"https://leetcode.com/problems/word-search/",                         difficulty:"Medium", xp:30 },
    { id:"bkt-q6", title:"Palindrome Partitioning",         url:"https://leetcode.com/problems/palindrome-partitioning/",             difficulty:"Medium", xp:30 },
    { id:"bkt-q7", title:"N-Queens",                        url:"https://leetcode.com/problems/n-queens/",                            difficulty:"Hard",   xp:40 },
  ]},
  { track:"searching", label:"Searching", color:"#3b82f6", questions:[
    { id:"sch-q1", title:"Search Insert Position",          url:"https://leetcode.com/problems/search-insert-position/",              difficulty:"Easy",   xp:20 },
    { id:"sch-q2", title:"Binary Search",                   url:"https://leetcode.com/problems/binary-search/",                       difficulty:"Easy",   xp:20 },
    { id:"sch-q3", title:"First Bad Version",               url:"https://leetcode.com/problems/first-bad-version/",                   difficulty:"Easy",   xp:20 },
    { id:"sch-q4", title:"Search a 2D Matrix",              url:"https://leetcode.com/problems/search-a-2d-matrix/",                  difficulty:"Medium", xp:30 },
    { id:"sch-q5", title:"Find Minimum in Rotated Sorted Array", url:"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty:"Medium", xp:30 },
    { id:"sch-q6", title:"Search in Rotated Sorted Array",  url:"https://leetcode.com/problems/search-in-rotated-sorted-array/",      difficulty:"Medium", xp:30 },
    { id:"sch-q7", title:"Koko Eating Bananas",             url:"https://leetcode.com/problems/koko-eating-bananas/",                 difficulty:"Medium", xp:30 },
  ]},
  { track:"sorting", label:"Sorting", color:"#f59e0b", questions:[
    { id:"srt-q1", title:"Sort Colors",                     url:"https://leetcode.com/problems/sort-colors/",                         difficulty:"Medium", xp:30 },
    { id:"srt-q2", title:"Sort an Array",                   url:"https://leetcode.com/problems/sort-an-array/",                       difficulty:"Medium", xp:30 },
    { id:"srt-q3", title:"Merge Sorted Array",              url:"https://leetcode.com/problems/merge-sorted-array/",                  difficulty:"Easy",   xp:20 },
    { id:"srt-q4", title:"Largest Number",                  url:"https://leetcode.com/problems/largest-number/",                      difficulty:"Medium", xp:30 },
    { id:"srt-q5", title:"K Closest Points to Origin",      url:"https://leetcode.com/problems/k-closest-points-to-origin/",         difficulty:"Medium", xp:30 },
    { id:"srt-q6", title:"Meeting Rooms",                   url:"https://leetcode.com/problems/meeting-rooms/",                       difficulty:"Easy",   xp:20 },
    { id:"srt-q7", title:"Merge Intervals",                 url:"https://leetcode.com/problems/merge-intervals/",                     difficulty:"Medium", xp:30 },
  ]},
  { track:"binary-search", label:"Binary Search", color:"#f59e0b", questions:[
    { id:"bin-q1", title:"Binary Search",                   url:"https://leetcode.com/problems/binary-search/",                       difficulty:"Easy",   xp:20 },
    { id:"bin-q2", title:"Find Minimum in Rotated Sorted Array", url:"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", difficulty:"Medium", xp:30 },
    { id:"bin-q3", title:"Search in Rotated Sorted Array",  url:"https://leetcode.com/problems/search-in-rotated-sorted-array/",      difficulty:"Medium", xp:30 },
    { id:"bin-q4", title:"Koko Eating Bananas",             url:"https://leetcode.com/problems/koko-eating-bananas/",                 difficulty:"Medium", xp:30 },
    { id:"bin-q5", title:"Time Based Key-Value Store",      url:"https://leetcode.com/problems/time-based-key-value-store/",          difficulty:"Medium", xp:30 },
    { id:"bin-q6", title:"Median of Two Sorted Arrays",     url:"https://leetcode.com/problems/median-of-two-sorted-arrays/",        difficulty:"Hard",   xp:40 },
    { id:"bin-q7", title:"Split Array Largest Sum",         url:"https://leetcode.com/problems/split-array-largest-sum/",             difficulty:"Hard",   xp:40 },
  ]},
  { track:"two-pointers", label:"Two Pointers", color:"#f59e0b", questions:[
    { id:"tp-q1", title:"Valid Palindrome",                  url:"https://leetcode.com/problems/valid-palindrome/",                    difficulty:"Easy",   xp:20 },
    { id:"tp-q2", title:"Two Sum II (Input Array Is Sorted)",url:"https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",   difficulty:"Medium", xp:30 },
    { id:"tp-q3", title:"3Sum",                              url:"https://leetcode.com/problems/3sum/",                               difficulty:"Medium", xp:30 },
    { id:"tp-q4", title:"Container With Most Water",         url:"https://leetcode.com/problems/container-with-most-water/",          difficulty:"Medium", xp:30 },
    { id:"tp-q5", title:"Trapping Rain Water",               url:"https://leetcode.com/problems/trapping-rain-water/",                difficulty:"Hard",   xp:40 },
    { id:"tp-q6", title:"Remove Duplicates from Sorted Array", url:"https://leetcode.com/problems/remove-duplicates-from-sorted-array/", difficulty:"Easy", xp:20 },
    { id:"tp-q7", title:"Move Zeroes",                       url:"https://leetcode.com/problems/move-zeroes/",                        difficulty:"Easy",   xp:20 },
  ]},
  { track:"sliding-win", label:"Sliding Window", color:"#f59e0b", questions:[
    { id:"sw-q1", title:"Best Time to Buy and Sell Stock",  url:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",     difficulty:"Easy",   xp:20 },
    { id:"sw-q2", title:"Longest Substring Without Repeating Characters", url:"https://leetcode.com/problems/longest-substring-without-repeating-characters/", difficulty:"Medium", xp:30 },
    { id:"sw-q3", title:"Longest Repeating Character Replacement", url:"https://leetcode.com/problems/longest-repeating-character-replacement/", difficulty:"Medium", xp:30 },
    { id:"sw-q4", title:"Permutation in String",            url:"https://leetcode.com/problems/permutation-in-string/",               difficulty:"Medium", xp:30 },
    { id:"sw-q5", title:"Minimum Window Substring",         url:"https://leetcode.com/problems/minimum-window-substring/",            difficulty:"Hard",   xp:40 },
    { id:"sw-q6", title:"Sliding Window Maximum",           url:"https://leetcode.com/problems/sliding-window-maximum/",              difficulty:"Hard",   xp:40 },
    { id:"sw-q7", title:"Find All Anagrams in a String",    url:"https://leetcode.com/problems/find-all-anagrams-in-a-string/",       difficulty:"Medium", xp:30 },
  ]},
  { track:"prefix-sum", label:"Prefix Sum", color:"#f59e0b", questions:[
    { id:"ps-q1", title:"Running Sum of 1d Array",          url:"https://leetcode.com/problems/running-sum-of-1d-array/",             difficulty:"Easy",   xp:20 },
    { id:"ps-q2", title:"Find Pivot Index",                 url:"https://leetcode.com/problems/find-pivot-index/",                    difficulty:"Easy",   xp:20 },
    { id:"ps-q3", title:"Subarray Sum Equals K",            url:"https://leetcode.com/problems/subarray-sum-equals-k/",              difficulty:"Medium", xp:30 },
    { id:"ps-q4", title:"Range Sum Query - Immutable",      url:"https://leetcode.com/problems/range-sum-query-immutable/",           difficulty:"Easy",   xp:20 },
    { id:"ps-q5", title:"Product of Array Except Self",     url:"https://leetcode.com/problems/product-of-array-except-self/",        difficulty:"Medium", xp:30 },
    { id:"ps-q6", title:"Maximum Size Subarray Sum Equals k", url:"https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/", difficulty:"Medium", xp:30 },
    { id:"ps-q7", title:"Count of Range Sum",               url:"https://leetcode.com/problems/count-of-range-sum/",                  difficulty:"Hard",   xp:40 },
  ]},
  { track:"bit-manip", label:"Bit Manipulation", color:"#ef4444", questions:[
    { id:"bm-q1", title:"Single Number",                    url:"https://leetcode.com/problems/single-number/",                       difficulty:"Easy",   xp:20 },
    { id:"bm-q2", title:"Number of 1 Bits",                 url:"https://leetcode.com/problems/number-of-1-bits/",                    difficulty:"Easy",   xp:20 },
    { id:"bm-q3", title:"Counting Bits",                    url:"https://leetcode.com/problems/counting-bits/",                       difficulty:"Easy",   xp:20 },
    { id:"bm-q4", title:"Reverse Bits",                     url:"https://leetcode.com/problems/reverse-bits/",                        difficulty:"Easy",   xp:20 },
    { id:"bm-q5", title:"Missing Number",                   url:"https://leetcode.com/problems/missing-number/",                      difficulty:"Easy",   xp:20 },
    { id:"bm-q6", title:"Sum of Two Integers",              url:"https://leetcode.com/problems/sum-of-two-integers/",                 difficulty:"Medium", xp:30 },
    { id:"bm-q7", title:"Reverse Integer",                  url:"https://leetcode.com/problems/reverse-integer/",                     difficulty:"Medium", xp:30 },
  ]},
  { track:"math", label:"Mathematics", color:"#f59e0b", questions:[
    { id:"mth-q1", title:"Palindrome Number",               url:"https://leetcode.com/problems/palindrome-number/",                   difficulty:"Easy",   xp:20 },
    { id:"mth-q2", title:"Happy Number",                    url:"https://leetcode.com/problems/happy-number/",                        difficulty:"Easy",   xp:20 },
    { id:"mth-q3", title:"Plus One",                        url:"https://leetcode.com/problems/plus-one/",                            difficulty:"Easy",   xp:20 },
    { id:"mth-q4", title:"Sqrt(x)",                         url:"https://leetcode.com/problems/sqrtx/",                               difficulty:"Easy",   xp:20 },
    { id:"mth-q5", title:"Pow(x, n)",                       url:"https://leetcode.com/problems/powx-n/",                              difficulty:"Medium", xp:30 },
    { id:"mth-q6", title:"Factorial Trailing Zeroes",       url:"https://leetcode.com/problems/factorial-trailing-zeroes/",           difficulty:"Medium", xp:30 },
    { id:"mth-q7", title:"Integer to Roman",                url:"https://leetcode.com/problems/integer-to-roman/",                    difficulty:"Medium", xp:30 },
  ]},
  { track:"number-theory", label:"Number Theory", color:"#ef4444", questions:[
    { id:"nt-q1", title:"Count Primes",                     url:"https://leetcode.com/problems/count-primes/",                        difficulty:"Medium", xp:30 },
    { id:"nt-q2", title:"Ugly Number",                      url:"https://leetcode.com/problems/ugly-number/",                         difficulty:"Easy",   xp:20 },
    { id:"nt-q3", title:"Ugly Number II",                   url:"https://leetcode.com/problems/ugly-number-ii/",                      difficulty:"Medium", xp:30 },
    { id:"nt-q4", title:"GCD of Strings",                   url:"https://leetcode.com/problems/greatest-common-divisor-of-strings/",  difficulty:"Easy",   xp:20 },
    { id:"nt-q5", title:"Nth Digit",                        url:"https://leetcode.com/problems/nth-digit/",                           difficulty:"Medium", xp:30 },
    { id:"nt-q6", title:"Super Pow",                        url:"https://leetcode.com/problems/super-pow/",                           difficulty:"Medium", xp:30 },
    { id:"nt-q7", title:"Minimum Operations to Make Array Divisible", url:"https://leetcode.com/problems/integer-replacement/",       difficulty:"Medium", xp:30 },
  ]},
  { track:"geometry", label:"Geometry", color:"#ef4444", questions:[
    { id:"geo-q1", title:"Valid Square",                    url:"https://leetcode.com/problems/valid-square/",                        difficulty:"Medium", xp:30 },
    { id:"geo-q2", title:"Max Points on a Line",            url:"https://leetcode.com/problems/max-points-on-a-line/",               difficulty:"Hard",   xp:40 },
    { id:"geo-q3", title:"Minimum Area Rectangle",          url:"https://leetcode.com/problems/minimum-area-rectangle/",             difficulty:"Medium", xp:30 },
    { id:"geo-q4", title:"K Closest Points to Origin",      url:"https://leetcode.com/problems/k-closest-points-to-origin/",         difficulty:"Medium", xp:30 },
    { id:"geo-q5", title:"Erect the Fence",                 url:"https://leetcode.com/problems/erect-the-fence/",                    difficulty:"Hard",   xp:40 },
    { id:"geo-q6", title:"Rectangle Overlap",               url:"https://leetcode.com/problems/rectangle-overlap/",                  difficulty:"Easy",   xp:20 },
    { id:"geo-q7", title:"Check If Two Rectangles Overlap", url:"https://leetcode.com/problems/rectangle-overlap/",                  difficulty:"Easy",   xp:20 },
  ]},
  { track:"divide-conquer", label:"Divide and Conquer", color:"#ef4444", questions:[
    { id:"dc-q1", title:"Merge Sort (Sort an Array)",       url:"https://leetcode.com/problems/sort-an-array/",                       difficulty:"Medium", xp:30 },
    { id:"dc-q2", title:"Kth Largest Element in Array",     url:"https://leetcode.com/problems/kth-largest-element-in-an-array/",    difficulty:"Medium", xp:30 },
    { id:"dc-q3", title:"Median of Two Sorted Arrays",      url:"https://leetcode.com/problems/median-of-two-sorted-arrays/",        difficulty:"Hard",   xp:40 },
    { id:"dc-q4", title:"Count of Smaller Numbers After Self", url:"https://leetcode.com/problems/count-of-smaller-numbers-after-self/", difficulty:"Hard", xp:40 },
    { id:"dc-q5", title:"Maximum Subarray",                 url:"https://leetcode.com/problems/maximum-subarray/",                    difficulty:"Medium", xp:30 },
    { id:"dc-q6", title:"Search a 2D Matrix II",            url:"https://leetcode.com/problems/search-a-2d-matrix-ii/",              difficulty:"Medium", xp:30 },
    { id:"dc-q7", title:"Beautiful Array",                  url:"https://leetcode.com/problems/beautiful-array/",                    difficulty:"Medium", xp:30 },
  ]},
  { track:"union-find", label:"Union Find (DSU)", color:"#ef4444", questions:[
    { id:"uf-q1", title:"Number of Provinces",              url:"https://leetcode.com/problems/number-of-provinces/",                 difficulty:"Medium", xp:30 },
    { id:"uf-q2", title:"Redundant Connection",             url:"https://leetcode.com/problems/redundant-connection/",               difficulty:"Medium", xp:30 },
    { id:"uf-q3", title:"Accounts Merge",                   url:"https://leetcode.com/problems/accounts-merge/",                      difficulty:"Medium", xp:30 },
    { id:"uf-q4", title:"Graph Valid Tree",                 url:"https://leetcode.com/problems/graph-valid-tree/",                    difficulty:"Medium", xp:30 },
    { id:"uf-q5", title:"Number of Connected Components",   url:"https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", difficulty:"Medium", xp:30 },
    { id:"uf-q6", title:"Making a Large Island",            url:"https://leetcode.com/problems/making-a-large-island/",               difficulty:"Hard",   xp:40 },
    { id:"uf-q7", title:"Satisfiability of Equality Equations", url:"https://leetcode.com/problems/satisfiability-of-equality-equations/", difficulty:"Medium", xp:30 },
  ]},
  { track:"segment-tree", label:"Segment Tree", color:"#ef4444", questions:[
    { id:"seg-q1", title:"Range Sum Query - Mutable",       url:"https://leetcode.com/problems/range-sum-query-mutable/",             difficulty:"Medium", xp:30 },
    { id:"seg-q2", title:"Count of Range Sum",              url:"https://leetcode.com/problems/count-of-range-sum/",                  difficulty:"Hard",   xp:40 },
    { id:"seg-q3", title:"The Skyline Problem",             url:"https://leetcode.com/problems/the-skyline-problem/",                 difficulty:"Hard",   xp:40 },
    { id:"seg-q4", title:"My Calendar I",                   url:"https://leetcode.com/problems/my-calendar-i/",                       difficulty:"Medium", xp:30 },
    { id:"seg-q5", title:"My Calendar III",                 url:"https://leetcode.com/problems/my-calendar-iii/",                     difficulty:"Hard",   xp:40 },
    { id:"seg-q6", title:"Falling Squares",                 url:"https://leetcode.com/problems/falling-squares/",                     difficulty:"Hard",   xp:40 },
    { id:"seg-q7", title:"Rectangle Area II",               url:"https://leetcode.com/problems/rectangle-area-ii/",                   difficulty:"Hard",   xp:40 },
  ]},
  { track:"fenwick", label:"Fenwick Tree (BIT)", color:"#ef4444", questions:[
    { id:"fen-q1", title:"Range Sum Query - Mutable",       url:"https://leetcode.com/problems/range-sum-query-mutable/",             difficulty:"Medium", xp:30 },
    { id:"fen-q2", title:"Count of Smaller Numbers After Self", url:"https://leetcode.com/problems/count-of-smaller-numbers-after-self/", difficulty:"Hard", xp:40 },
    { id:"fen-q3", title:"Reverse Pairs",                   url:"https://leetcode.com/problems/reverse-pairs/",                       difficulty:"Hard",   xp:40 },
    { id:"fen-q4", title:"Count of Range Sum",              url:"https://leetcode.com/problems/count-of-range-sum/",                  difficulty:"Hard",   xp:40 },
    { id:"fen-q5", title:"Create Sorted Array through Instructions", url:"https://leetcode.com/problems/create-sorted-array-through-instructions/", difficulty:"Hard", xp:40 },
    { id:"fen-q6", title:"Number of Longest Increasing Subsequence", url:"https://leetcode.com/problems/number-of-longest-increasing-subsequence/", difficulty:"Medium", xp:30 },
    { id:"fen-q7", title:"The Number of Weak Characters in the Game", url:"https://leetcode.com/problems/the-number-of-weak-characters-in-the-game/", difficulty:"Medium", xp:30 },
  ]},
  { track:"mono-stack", label:"Monotonic Stack", color:"#ef4444", questions:[
    { id:"ms-q1", title:"Daily Temperatures",               url:"https://leetcode.com/problems/daily-temperatures/",                  difficulty:"Medium", xp:30 },
    { id:"ms-q2", title:"Next Greater Element I",           url:"https://leetcode.com/problems/next-greater-element-i/",              difficulty:"Easy",   xp:20 },
    { id:"ms-q3", title:"Next Greater Element II",          url:"https://leetcode.com/problems/next-greater-element-ii/",             difficulty:"Medium", xp:30 },
    { id:"ms-q4", title:"Largest Rectangle in Histogram",   url:"https://leetcode.com/problems/largest-rectangle-in-histogram/",     difficulty:"Hard",   xp:40 },
    { id:"ms-q5", title:"Trapping Rain Water",              url:"https://leetcode.com/problems/trapping-rain-water/",                 difficulty:"Hard",   xp:40 },
    { id:"ms-q6", title:"Remove K Digits",                  url:"https://leetcode.com/problems/remove-k-digits/",                     difficulty:"Medium", xp:30 },
    { id:"ms-q7", title:"Sum of Subarray Minimums",         url:"https://leetcode.com/problems/sum-of-subarray-minimums/",            difficulty:"Medium", xp:30 },
  ]},
  { track:"mono-queue", label:"Monotonic Queue", color:"#ef4444", questions:[
    { id:"mq-q1", title:"Sliding Window Maximum",           url:"https://leetcode.com/problems/sliding-window-maximum/",              difficulty:"Hard",   xp:40 },
    { id:"mq-q2", title:"Jump Game VI",                     url:"https://leetcode.com/problems/jump-game-vi/",                        difficulty:"Medium", xp:30 },
    { id:"mq-q3", title:"Constrained Subsequence Sum",      url:"https://leetcode.com/problems/constrained-subsequence-sum/",         difficulty:"Hard",   xp:40 },
    { id:"mq-q4", title:"Shortest Subarray with Sum K",     url:"https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/", difficulty:"Hard", xp:40 },
    { id:"mq-q5", title:"Max Value of Equation",            url:"https://leetcode.com/problems/max-value-of-equation/",               difficulty:"Hard",   xp:40 },
    { id:"mq-q6", title:"Sliding Window Median",            url:"https://leetcode.com/problems/sliding-window-median/",               difficulty:"Hard",   xp:40 },
    { id:"mq-q7", title:"Minimum Number of Increments on Subarrays", url:"https://leetcode.com/problems/minimum-number-of-increments-on-subarrays/", difficulty:"Hard", xp:40 },
  ]},
  { track:"topo-sort", label:"Topological Sort", color:"#8b5cf6", questions:[
    { id:"ts-q1", title:"Course Schedule",                  url:"https://leetcode.com/problems/course-schedule/",                     difficulty:"Medium", xp:30 },
    { id:"ts-q2", title:"Course Schedule II",               url:"https://leetcode.com/problems/course-schedule-ii/",                  difficulty:"Medium", xp:30 },
    { id:"ts-q3", title:"Alien Dictionary",                 url:"https://leetcode.com/problems/alien-dictionary/",                    difficulty:"Hard",   xp:40 },
    { id:"ts-q4", title:"Sequence Reconstruction",          url:"https://leetcode.com/problems/sequence-reconstruction/",             difficulty:"Medium", xp:30 },
    { id:"ts-q5", title:"Find All Possible Recipes",        url:"https://leetcode.com/problems/find-all-possible-recipes-from-given-supplies/", difficulty:"Medium", xp:30 },
    { id:"ts-q6", title:"Minimum Height Trees",             url:"https://leetcode.com/problems/minimum-height-trees/",               difficulty:"Medium", xp:30 },
    { id:"ts-q7", title:"Sort Items by Groups",             url:"https://leetcode.com/problems/sort-items-by-groups-respecting-dependencies/", difficulty:"Hard", xp:40 },
  ]},
  { track:"bfs", label:"Breadth-First Search (BFS)", color:"#8b5cf6", questions:[
    { id:"bfs-q1", title:"Binary Tree Level Order Traversal", url:"https://leetcode.com/problems/binary-tree-level-order-traversal/",difficulty:"Medium", xp:30 },
    { id:"bfs-q2", title:"Rotting Oranges",                  url:"https://leetcode.com/problems/rotting-oranges/",                    difficulty:"Medium", xp:30 },
    { id:"bfs-q3", title:"Walls and Gates",                  url:"https://leetcode.com/problems/walls-and-gates/",                    difficulty:"Medium", xp:30 },
    { id:"bfs-q4", title:"Word Ladder",                      url:"https://leetcode.com/problems/word-ladder/",                        difficulty:"Hard",   xp:40 },
    { id:"bfs-q5", title:"Open the Lock",                    url:"https://leetcode.com/problems/open-the-lock/",                      difficulty:"Medium", xp:30 },
    { id:"bfs-q6", title:"Jump Game III",                    url:"https://leetcode.com/problems/jump-game-iii/",                      difficulty:"Medium", xp:30 },
    { id:"bfs-q7", title:"Shortest Path in Binary Matrix",   url:"https://leetcode.com/problems/shortest-path-in-binary-matrix/",    difficulty:"Medium", xp:30 },
  ]},
  { track:"dfs", label:"Depth-First Search (DFS)", color:"#8b5cf6", questions:[
    { id:"dfs-q1", title:"Number of Islands",               url:"https://leetcode.com/problems/number-of-islands/",                   difficulty:"Medium", xp:30 },
    { id:"dfs-q2", title:"Clone Graph",                     url:"https://leetcode.com/problems/clone-graph/",                         difficulty:"Medium", xp:30 },
    { id:"dfs-q3", title:"Pacific Atlantic Water Flow",     url:"https://leetcode.com/problems/pacific-atlantic-water-flow/",         difficulty:"Medium", xp:30 },
    { id:"dfs-q4", title:"Surrounded Regions",              url:"https://leetcode.com/problems/surrounded-regions/",                  difficulty:"Medium", xp:30 },
    { id:"dfs-q5", title:"Course Schedule",                 url:"https://leetcode.com/problems/course-schedule/",                     difficulty:"Medium", xp:30 },
    { id:"dfs-q6", title:"Island Perimeter",                url:"https://leetcode.com/problems/island-perimeter/",                    difficulty:"Easy",   xp:20 },
    { id:"dfs-q7", title:"Keys and Rooms",                  url:"https://leetcode.com/problems/keys-and-rooms/",                      difficulty:"Medium", xp:30 },
  ]},
  { track:"shortest-path", label:"Shortest Path Algorithms", color:"#8b5cf6", questions:[
    { id:"sp-q1", title:"Network Delay Time",               url:"https://leetcode.com/problems/network-delay-time/",                  difficulty:"Medium", xp:30 },
    { id:"sp-q2", title:"Cheapest Flights Within K Stops",  url:"https://leetcode.com/problems/cheapest-flights-within-k-stops/",    difficulty:"Medium", xp:30 },
    { id:"sp-q3", title:"Path With Minimum Effort",         url:"https://leetcode.com/problems/path-with-minimum-effort/",           difficulty:"Medium", xp:30 },
    { id:"sp-q4", title:"Find the City With Fewest Reachable Neighbours", url:"https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/", difficulty:"Medium", xp:30 },
    { id:"sp-q5", title:"Swim in Rising Water",             url:"https://leetcode.com/problems/swim-in-rising-water/",               difficulty:"Hard",   xp:40 },
    { id:"sp-q6", title:"Minimum Cost to Connect All Points", url:"https://leetcode.com/problems/min-cost-to-connect-all-points/",   difficulty:"Medium", xp:30 },
    { id:"sp-q7", title:"Word Ladder",                      url:"https://leetcode.com/problems/word-ladder/",                        difficulty:"Hard",   xp:40 },
  ]},
  { track:"mst", label:"Minimum Spanning Tree (MST)", color:"#8b5cf6", questions:[
    { id:"mst-q1", title:"Min Cost to Connect All Points",  url:"https://leetcode.com/problems/min-cost-to-connect-all-points/",     difficulty:"Medium", xp:30 },
    { id:"mst-q2", title:"Connecting Cities With Minimum Cost", url:"https://leetcode.com/problems/connecting-cities-with-minimum-cost/", difficulty:"Medium", xp:30 },
    { id:"mst-q3", title:"Redundant Connection",            url:"https://leetcode.com/problems/redundant-connection/",               difficulty:"Medium", xp:30 },
    { id:"mst-q4", title:"Optimize Water Distribution",     url:"https://leetcode.com/problems/optimize-water-distribution-in-a-village/", difficulty:"Hard", xp:40 },
    { id:"mst-q5", title:"Find Critical and Pseudo-Critical Edges", url:"https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/", difficulty:"Hard", xp:40 },
    { id:"mst-q6", title:"Remove Max Number of Edges",      url:"https://leetcode.com/problems/remove-max-number-of-edges-to-keep-graph-fully-traversable/", difficulty:"Hard", xp:40 },
    { id:"mst-q7", title:"Checking Existence of Edge Length Limited Paths", url:"https://leetcode.com/problems/checking-existence-of-edge-length-limited-paths/", difficulty:"Hard", xp:40 },
  ]},
  { track:"lca", label:"Lowest Common Ancestor (LCA)", color:"#8b5cf6", questions:[
    { id:"lca-q1", title:"LCA of Binary Tree",              url:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", difficulty:"Medium", xp:30 },
    { id:"lca-q2", title:"LCA of BST",                      url:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/", difficulty:"Medium", xp:30 },
    { id:"lca-q3", title:"LCA of Deepest Leaves",           url:"https://leetcode.com/problems/lowest-common-ancestor-of-deepest-leaves/", difficulty:"Medium", xp:30 },
    { id:"lca-q4", title:"Kth Ancestor of Tree Node",       url:"https://leetcode.com/problems/kth-ancestor-of-a-tree-node/",        difficulty:"Hard",   xp:40 },
    { id:"lca-q5", title:"Distance Between Nodes in BST",   url:"https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/",difficulty:"Medium", xp:30 },
    { id:"lca-q6", title:"Step-By-Step Directions From Binary Tree Node", url:"https://leetcode.com/problems/step-by-step-directions-from-a-binary-tree-node-to-another/", difficulty:"Medium", xp:30 },
    { id:"lca-q7", title:"Maximum Difference Between Node and Ancestor", url:"https://leetcode.com/problems/maximum-difference-between-node-and-ancestor/", difficulty:"Medium", xp:30 },
  ]},
  { track:"string-algo", label:"String Algorithms", color:"#ef4444", questions:[
    { id:"sa-q1", title:"Implement strStr()",               url:"https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/", difficulty:"Easy", xp:20 },
    { id:"sa-q2", title:"Repeated Substring Pattern",       url:"https://leetcode.com/problems/repeated-substring-pattern/",          difficulty:"Easy",   xp:20 },
    { id:"sa-q3", title:"Shortest Palindrome (KMP)",        url:"https://leetcode.com/problems/shortest-palindrome/",                 difficulty:"Hard",   xp:40 },
    { id:"sa-q4", title:"Longest Duplicate Substring",      url:"https://leetcode.com/problems/longest-duplicate-substring/",         difficulty:"Hard",   xp:40 },
    { id:"sa-q5", title:"Minimum Window Substring",         url:"https://leetcode.com/problems/minimum-window-substring/",            difficulty:"Hard",   xp:40 },
    { id:"sa-q6", title:"Find All Anagrams in String",      url:"https://leetcode.com/problems/find-all-anagrams-in-a-string/",       difficulty:"Medium", xp:30 },
    { id:"sa-q7", title:"Rabin-Karp Rolling Hash",          url:"https://leetcode.com/problems/longest-duplicate-substring/",         difficulty:"Hard",   xp:40 },
  ]},
  { track:"comp-geo", label:"Computational Geometry", color:"#8b5cf6", questions:[
    { id:"cg-q1", title:"Max Points on a Line",             url:"https://leetcode.com/problems/max-points-on-a-line/",               difficulty:"Hard",   xp:40 },
    { id:"cg-q2", title:"Erect the Fence",                  url:"https://leetcode.com/problems/erect-the-fence/",                    difficulty:"Hard",   xp:40 },
    { id:"cg-q3", title:"Minimum Area Rectangle",           url:"https://leetcode.com/problems/minimum-area-rectangle/",             difficulty:"Medium", xp:30 },
    { id:"cg-q4", title:"Valid Boomerang",                  url:"https://leetcode.com/problems/valid-boomerang/",                    difficulty:"Easy",   xp:20 },
    { id:"cg-q5", title:"Largest Triangle Area",            url:"https://leetcode.com/problems/largest-triangle-area/",             difficulty:"Easy",   xp:20 },
    { id:"cg-q6", title:"Rectangle Area",                   url:"https://leetcode.com/problems/rectangle-area/",                    difficulty:"Medium", xp:30 },
    { id:"cg-q7", title:"Minimum Area Rectangle II",        url:"https://leetcode.com/problems/minimum-area-rectangle-ii/",         difficulty:"Medium", xp:30 },
  ]},
  { track:"game-theory", label:"Game Theory", color:"#8b5cf6", questions:[
    { id:"gt-q1", title:"Nim Game",                         url:"https://leetcode.com/problems/nim-game/",                           difficulty:"Easy",   xp:20 },
    { id:"gt-q2", title:"Flip Game II",                     url:"https://leetcode.com/problems/flip-game-ii/",                       difficulty:"Medium", xp:30 },
    { id:"gt-q3", title:"Predict the Winner",               url:"https://leetcode.com/problems/predict-the-winner/",                 difficulty:"Medium", xp:30 },
    { id:"gt-q4", title:"Stone Game",                       url:"https://leetcode.com/problems/stone-game/",                         difficulty:"Medium", xp:30 },
    { id:"gt-q5", title:"Stone Game II",                    url:"https://leetcode.com/problems/stone-game-ii/",                      difficulty:"Medium", xp:30 },
    { id:"gt-q6", title:"Cat and Mouse",                    url:"https://leetcode.com/problems/cat-and-mouse/",                      difficulty:"Hard",   xp:40 },
    { id:"gt-q7", title:"Zuma Game",                        url:"https://leetcode.com/problems/zuma-game/",                          difficulty:"Hard",   xp:40 },
  ]},
  { track:"probability", label:"Probability", color:"#8b5cf6", questions:[
    { id:"prob-q1", title:"Random Pick with Weight",        url:"https://leetcode.com/problems/random-pick-with-weight/",             difficulty:"Medium", xp:30 },
    { id:"prob-q2", title:"Random Pick Index",              url:"https://leetcode.com/problems/random-pick-index/",                   difficulty:"Medium", xp:30 },
    { id:"prob-q3", title:"Shuffle an Array",               url:"https://leetcode.com/problems/shuffle-an-array/",                   difficulty:"Medium", xp:30 },
    { id:"prob-q4", title:"Implement Rand10 Using Rand7",   url:"https://leetcode.com/problems/implement-rand10-using-rand7/",       difficulty:"Medium", xp:30 },
    { id:"prob-q5", title:"Generate Random Point in Circle",url:"https://leetcode.com/problems/generate-random-point-in-a-circle/",  difficulty:"Medium", xp:30 },
    { id:"prob-q6", title:"Random Point in Non-overlapping Rectangles", url:"https://leetcode.com/problems/random-point-in-non-overlapping-rectangles/", difficulty:"Medium", xp:30 },
    { id:"prob-q7", title:"Maximum Profit in Job Scheduling",url:"https://leetcode.com/problems/maximum-profit-in-job-scheduling/",  difficulty:"Hard",   xp:40 },
  ]},
  { track:"sql", label:"SQL", color:"#06b6d4", questions:[
    { id:"sql-q1", title:"Combine Two Tables",              url:"https://leetcode.com/problems/combine-two-tables/",                  difficulty:"Easy",   xp:20 },
    { id:"sql-q2", title:"Second Highest Salary",           url:"https://leetcode.com/problems/second-highest-salary/",              difficulty:"Medium", xp:30 },
    { id:"sql-q3", title:"Employees Earning More Than Managers", url:"https://leetcode.com/problems/employees-earning-more-than-their-managers/", difficulty:"Easy", xp:20 },
    { id:"sql-q4", title:"Duplicate Emails",                url:"https://leetcode.com/problems/duplicate-emails/",                   difficulty:"Easy",   xp:20 },
    { id:"sql-q5", title:"Rank Scores",                     url:"https://leetcode.com/problems/rank-scores/",                        difficulty:"Medium", xp:30 },
    { id:"sql-q6", title:"Department Top Three Salaries",   url:"https://leetcode.com/problems/department-top-three-salaries/",      difficulty:"Hard",   xp:40 },
    { id:"sql-q7", title:"Consecutive Numbers",             url:"https://leetcode.com/problems/consecutive-numbers/",                difficulty:"Medium", xp:30 },
  ]},
  { track:"oop", label:"Object-Oriented Programming (OOP)", color:"#f59e0b", questions:[
    { id:"oop-q1", title:"Design Parking System",           url:"https://leetcode.com/problems/design-parking-system/",              difficulty:"Easy",   xp:20 },
    { id:"oop-q2", title:"Design HashMap",                  url:"https://leetcode.com/problems/design-hashmap/",                     difficulty:"Easy",   xp:20 },
    { id:"oop-q3", title:"LRU Cache",                       url:"https://leetcode.com/problems/lru-cache/",                           difficulty:"Medium", xp:30 },
    { id:"oop-q4", title:"Design Twitter",                  url:"https://leetcode.com/problems/design-twitter/",                      difficulty:"Medium", xp:30 },
    { id:"oop-q5", title:"Design Hit Counter",              url:"https://leetcode.com/problems/design-hit-counter/",                  difficulty:"Medium", xp:30 },
    { id:"oop-q6", title:"Implement Stack Using Queues",    url:"https://leetcode.com/problems/implement-stack-using-queues/",        difficulty:"Easy",   xp:20 },
    { id:"oop-q7", title:"Design Snake Game",               url:"https://leetcode.com/problems/design-snake-game/",                   difficulty:"Medium", xp:30 },
  ]},
  { track:"complexity", label:"Time & Space Complexity", color:"#f59e0b", questions:[
    { id:"cmp-q1", title:"Two Sum (O(n) hash solution)",    url:"https://leetcode.com/problems/two-sum/",                             difficulty:"Easy",   xp:20 },
    { id:"cmp-q2", title:"Contains Duplicate (O(n) set)",  url:"https://leetcode.com/problems/contains-duplicate/",                  difficulty:"Easy",   xp:20 },
    { id:"cmp-q3", title:"Binary Search (O(log n))",        url:"https://leetcode.com/problems/binary-search/",                       difficulty:"Easy",   xp:20 },
    { id:"cmp-q4", title:"Merge Sort (O(n log n))",         url:"https://leetcode.com/problems/sort-an-array/",                       difficulty:"Medium", xp:30 },
    { id:"cmp-q5", title:"Longest Common Subsequence (O(mn) DP)", url:"https://leetcode.com/problems/longest-common-subsequence/",   difficulty:"Medium", xp:30 },
    { id:"cmp-q6", title:"LRU Cache (O(1) operations)",     url:"https://leetcode.com/problems/lru-cache/",                           difficulty:"Medium", xp:30 },
    { id:"cmp-q7", title:"Median of Two Sorted Arrays (O(log(min(m,n))))", url:"https://leetcode.com/problems/median-of-two-sorted-arrays/", difficulty:"Hard", xp:40 },
  ]},
  { track:"design-patterns", label:"Design Patterns", color:"#8b5cf6", questions:[
    { id:"dp2-q1", title:"Implement Singleton (LRU Cache)", url:"https://leetcode.com/problems/lru-cache/",                           difficulty:"Medium", xp:30 },
    { id:"dp2-q2", title:"Observer Pattern (Design Twitter)",url:"https://leetcode.com/problems/design-twitter/",                    difficulty:"Medium", xp:30 },
    { id:"dp2-q3", title:"Iterator Pattern (Flatten 2D Vector)", url:"https://leetcode.com/problems/flatten-2d-vector/",             difficulty:"Medium", xp:30 },
    { id:"dp2-q4", title:"Factory Pattern (Design HashMap)",url:"https://leetcode.com/problems/design-hashmap/",                     difficulty:"Easy",   xp:20 },
    { id:"dp2-q5", title:"Strategy Pattern (Sort Colors)",  url:"https://leetcode.com/problems/sort-colors/",                        difficulty:"Medium", xp:30 },
    { id:"dp2-q6", title:"Decorator Pattern (Logger Rate Limiter)", url:"https://leetcode.com/problems/logger-rate-limiter/",        difficulty:"Easy",   xp:20 },
    { id:"dp2-q7", title:"Command Pattern (Design Phone Directory)", url:"https://leetcode.com/problems/design-phone-directory/",    difficulty:"Medium", xp:30 },
  ]},
  { track:"dbms", label:"Database Management Systems (DBMS)", color:"#8b5cf6", questions:[
    { id:"db-q1", title:"Rising Temperature",               url:"https://leetcode.com/problems/rising-temperature/",                  difficulty:"Easy",   xp:20 },
    { id:"db-q2", title:"Customer Who Visited but Made No Transactions", url:"https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/", difficulty:"Easy", xp:20 },
    { id:"db-q3", title:"Trips and Users",                  url:"https://leetcode.com/problems/trips-and-users/",                     difficulty:"Hard",   xp:40 },
    { id:"db-q4", title:"Department Highest Salary",        url:"https://leetcode.com/problems/department-highest-salary/",           difficulty:"Medium", xp:30 },
    { id:"db-q5", title:"Median Employee Salary",           url:"https://leetcode.com/problems/median-employee-salary/",              difficulty:"Hard",   xp:40 },
    { id:"db-q6", title:"Get Highest Answer Rate Question", url:"https://leetcode.com/problems/get-highest-answer-rate-question/",    difficulty:"Medium", xp:30 },
    { id:"db-q7", title:"Friend Requests II: Who Has Most Friends", url:"https://leetcode.com/problems/friend-requests-ii-who-has-the-most-friends/", difficulty:"Medium", xp:30 },
  ]},
  { track:"system-design", label:"System Design", color:"#8b5cf6", questions:[
    { id:"sd-q1", title:"LRU Cache",                        url:"https://leetcode.com/problems/lru-cache/",                           difficulty:"Medium", xp:30 },
    { id:"sd-q2", title:"LFU Cache",                        url:"https://leetcode.com/problems/lfu-cache/",                           difficulty:"Hard",   xp:40 },
    { id:"sd-q3", title:"Design Twitter",                   url:"https://leetcode.com/problems/design-twitter/",                      difficulty:"Medium", xp:30 },
    { id:"sd-q4", title:"Design File System",               url:"https://leetcode.com/problems/design-file-system/",                  difficulty:"Medium", xp:30 },
    { id:"sd-q5", title:"Design In-Memory File System",     url:"https://leetcode.com/problems/design-in-memory-file-system/",        difficulty:"Hard",   xp:40 },
    { id:"sd-q6", title:"Design Search Autocomplete",       url:"https://leetcode.com/problems/design-search-autocomplete-system/",   difficulty:"Hard",   xp:40 },
    { id:"sd-q7", title:"Snapshot Array",                   url:"https://leetcode.com/problems/snapshot-array/",                      difficulty:"Medium", xp:30 },
  ]},
  { track:"git", label:"Git", color:"#f59e0b", questions:[
    { id:"git-q1", title:"Link GitHub profile",             url:"https://github.com/",                                                difficulty:"Easy",   xp:20 },
    { id:"git-q2", title:"Create a public repository",      url:"https://github.com/new",                                             difficulty:"Easy",   xp:20 },
    { id:"git-q3", title:"Make first commit",               url:"https://docs.github.com/en/get-started/quickstart/create-a-repo",   difficulty:"Easy",   xp:20 },
    { id:"git-q4", title:"10 total commits",                url:"https://skills.github.com/",                                         difficulty:"Easy",   xp:20 },
    { id:"git-q5", title:"Create a Pull Request",           url:"https://docs.github.com/en/pull-requests",                          difficulty:"Medium", xp:30 },
    { id:"git-q6", title:"50 total commits",                url:"https://skills.github.com/",                                         difficulty:"Medium", xp:30 },
    { id:"git-q7", title:"100 total commits",               url:"https://skills.github.com/",                                         difficulty:"Hard",   xp:40 },
  ]},
]

export function getTopicByTrack(track: string): TopicData | undefined {
  return TOPIC_QUESTIONS.find(t => t.track === track)
}
