/**
 * POST /api/student/company-coding-ai
 * CodeHiring's own coding question model.
 *
 * Priority chain:
 * 1. MongoDB DB (18,900 pre-seeded problems) — instant, shuffled
 * 2. Static banks (service/fintech/it-services) — RAG examples for AI
 * 3. AI generation with company profile + pattern templates
 * 4. Static bank direct return (no AI)
 *
 * Body: { company, section?, count?, difficulty? }
 */

import { NextResponse } from "next/server"
import { ALL_COMPANIES } from "@/lib/companies-data"
import { getCompanyCodingProfile } from "@/lib/coding-model/company-profiles"
import { buildModelPrompt, formatRAGExamples, selectBatchPatterns } from "@/lib/coding-model/generator"
import { getProblemsForCompany, countProblemsForCompany, getCompanyProblemsCollection } from "@/lib/models/company-problem"
import { SERVICE_PROBLEM_BANK } from "@/lib/service-company-problems"
import { FINTECH_PROBLEM_BANK } from "@/lib/fintech-problem-bank"

const GROQ_API   = "https://api.groq.com/openai/v1/chat/completions"
const OPENAI_API = "https://api.openai.com/v1/chat/completions"

async function callAI(systemPrompt: string, userPrompt: string, maxTokens = 6000): Promise<string> {
  const msgs = [{ role: "system", content: systemPrompt }, { role: "user", content: userPrompt }]

  if (process.env.OPENAI_API_KEY) {
    try {
      const r = await fetch(OPENAI_API, {
        method: "POST",
        headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}`, "Content-Type": "application/json" },
        body: JSON.stringify({ model: "gpt-4o-mini", messages: msgs, temperature: 0.85, max_tokens: maxTokens }),
      })
      if (r.ok) { const d = await r.json(); const t = d.choices?.[0]?.message?.content?.trim(); if (t) return t }
    } catch {}
  }

  if (process.env.GROQ_API_KEY) {
    const r = await fetch(GROQ_API, {
      method: "POST",
      headers: { Authorization: `Bearer ${process.env.GROQ_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model: "llama-3.3-70b-versatile", messages: msgs, temperature: 0.85, max_tokens: maxTokens }),
    })
    if (r.ok) { const d = await r.json(); return d.choices?.[0]?.message?.content?.trim() ?? "" }
  }
  throw new Error("No AI provider available")
}

/** Pull static RAG examples for a company from all problem banks */
function getStaticExamples(companyId: string, limit = 5): any[] {
  const normId = companyId.replace(/-/g, "")
  const allBanks: Record<string, any> = { ...SERVICE_PROBLEM_BANK, ...FINTECH_PROBLEM_BANK }
  try {
    const { IT_SERVICES_PROBLEM_BANK } = require("@/lib/it-services-problems")
    Object.assign(allBanks, IT_SERVICES_PROBLEM_BANK)
  } catch {}

  const direct = Object.values(allBanks).filter((p: any) => p.company === normId || p.company === companyId)
  if (direct.length >= 3) return direct.sort(() => Math.random() - 0.5).slice(0, limit)

  const co = ALL_COMPANIES.find(c => c.id === companyId)
  const similarIds = ALL_COMPANIES.filter(c => c.category === co?.category && c.id !== companyId).map(c => c.id.replace(/-/g, ""))
  const fallback = Object.values(allBanks).filter((p: any) => similarIds.includes(p.company))
  return [...direct, ...fallback].sort(() => Math.random() - 0.5).slice(0, limit)
}

/** Format DB problems to the API response shape */
function formatDbProblems(problems: any[]) {
  return problems.map((p, i) => ({
    id: i + 1,
    title: p.title,
    difficulty: p.difficulty,
    topic: p.pattern,
    statement: p.statement,
    constraints: p.constraints,
    example: p.examples?.[0] ?? { input: "", output: "", explanation: "" },
    hints: p.hints ?? [],
  }))
}

export async function POST(req: Request) {
  try {
    const body = await req.json()
    const companyId: string = body.company ?? ""
    const sectionId: string = body.section ?? "coding"
    const count: number = Math.min(body.count ?? 3, 10)
    const requestedDiff: string = body.difficulty ?? ""

    if (!companyId) return NextResponse.json({ error: "company is required" }, { status: 400 })

    const co = ALL_COMPANIES.find(c => c.id === companyId)
    const companyName = co?.name ?? companyId
    const category = co?.category ?? "IT Services"

    // ── 1. MongoDB first (AI-generated problems already seeded) ──────────────
    try {
      const dbCount = await countProblemsForCompany(companyId)
      if (dbCount >= count) {
        const dbProblems = await getProblemsForCompany(companyId, {
          difficulty: requestedDiff || undefined,
          count,
          shuffle: true,
        })
        if (dbProblems.length >= count) {
          return NextResponse.json({
            questions: formatDbProblems(dbProblems),
            company: companyName,
            section: sectionId,
            source: "ai_database",   // all DB problems were AI-generated by the seeder
            totalAvailable: dbCount,
          })
        }
      }
    } catch { /* DB unavailable, continue to live AI */ }

    // ── 2. No DB or insufficient problems → live AI generation ───────────────
    // (This also runs when the seeder hasn't run yet for this company)
    const profile = getCompanyCodingProfile(companyId, category)
    const section = profile?.sections[sectionId] ?? profile?.sections["coding"] ?? {
      name: "Coding", description: "", count, timeMinutes: 60, difficulty: "Medium" as const,
      patterns: ["Array Traversal","String Manipulation","Sorting","Hash Map","Basic DP"],
      constraints: { arraySize: "1 <= n <= 10^4", stringLen: "1 <= s.length <= 500", treeNodes: "N/A", graphNodes: "N/A" },
      style: ["Clear problem statement", "2 examples"], avoidPatterns: [],
    }

    const staticExamples = getStaticExamples(companyId, 5)
    const ragText = formatRAGExamples(staticExamples, 4)
    const batchPatterns = selectBatchPatterns(section, 0, Math.max(1, count))

    // ── 3. No AI provider — cannot serve without AI ───────────────────────────
    if (!process.env.GROQ_API_KEY && !process.env.OPENAI_API_KEY) {
      return NextResponse.json({
        error: "No AI provider configured. Set GROQ_API_KEY or OPENAI_API_KEY to generate company-specific coding questions.",
      }, { status: 503 })
    }

    // ── 4. AI generation using company profile ────────────────────────────────
    const systemPrompt = buildModelPrompt(
      section, companyName, category,
      profile?.realExamNotes ?? "",
      profile?.globalStyle ?? [],
      ragText,
      batchPatterns,
      count,
    )

    const userPrompt = `Generate ${count} ${requestedDiff || section.difficulty} coding problems for ${companyName}'s ${section.name}.\n\nReturn ONLY valid JSON array.`

    const raw = await callAI(systemPrompt, userPrompt, 6000)
    const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim()
    const parsed = JSON.parse(cleaned)
    const questions: any[] = Array.isArray(parsed) ? parsed : (parsed.questions ?? [])

    // ── 5. Cache to MongoDB ───────────────────────────────────────────────────
    if (questions.length > 0) {
      try {
        const col = await getCompanyProblemsCollection()
        const docs = questions.map((p: any) => ({
          company: co?.id ?? companyId, companyName, category,
          title: p.title ?? "Untitled",
          difficulty: (["Easy","Medium","Hard"].includes(p.difficulty) ? p.difficulty : "Medium") as "Easy"|"Medium"|"Hard",
          pattern: p.pattern ?? p.topic ?? "Unknown",
          topic: p.topic ?? p.pattern ?? "",
          statement: p.statement ?? "",
          constraints: p.constraints ?? "",
          examples: p.examples ?? (p.example ? [p.example] : []),
          hints: p.hints ?? [],
          tags: [companyId, (p.difficulty ?? "medium").toLowerCase()],
          createdAt: new Date(),
          generatedBy: "groq" as const,
          batchId: `live_${Date.now()}`,
        }))
        await col.insertMany(docs, { ordered: false }).catch(() => {})
      } catch { /* silent cache failure */ }
    }

    return NextResponse.json({
      questions: questions.map((q: any, i: number) => ({
        id: i + 1,
        title: q.title, difficulty: q.difficulty, topic: q.topic ?? q.pattern,
        statement: q.statement,
        constraints: q.constraints,
        example: q.examples?.[0] ?? q.example ?? { input: "", output: "", explanation: "" },
        hints: q.hints ?? [],
        functionSignature: q.functionSignature,
      })),
      company: companyName, section: section.name, source: "ai_generated",
      patternsUsed: batchPatterns,
    })

  } catch (err: any) {
    console.error("company-coding-ai error:", err)
    return NextResponse.json({ error: err.message ?? "Generation failed" }, { status: 500 })
  }
}
